name: Build and deploy ASP.Net Core app to Azure Web App - MantaRaysWeather

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: MantaRaysWeather
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '8.0'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build --configuration Release MantaCloud_Weather/MantaRays_Weather.csproj

      - name: dotnet publish
        run: dotnet publish MantaCloud_Weather/MantaRays_Weather.csproj -c Release -o ${{ github.workspace }}/myapp

      - name: List publish directory contents
        run: Get-ChildItem -Path ${{ github.workspace }}/myapp -Recurse

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./

      - name: List downloaded artifact contents
        run: Get-ChildItem -Path . -Recurse

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Set environment variables
        env:
          APPLICATIONINSIGHTS_CONNECTION_STRING: ${{ secrets.APPLICATIONINSIGHTS_CONNECTION_STRING }}
          ApplicationInsights__ConnectionString: ${{ secrets.ApplicationInsights__ConnectionString }}
          ApplicationInsights__LogLevel__Default: ${{ secrets.APPLICATIONINSIGHTS__LogLevel__Default }}
          APIs__NationalWeatherService__Uri: ${{ secrets.APIs__NationalWeatherService__Uri }}
          APIs__NationalWeatherService__UserAgent: ${{ secrets.APIs__NationalWeatherService__UserAgent }}
          APIs__NWSPointLocation__Uri: ${{ secrets.APIs__NWSPointLocation__Uri }}
          APIs__NWSPointLocation__UserAgent: ${{ secrets.APIs__NWSPointLocation__UserAgent }}
          APIs__GeoCode__Uri: ${{ secrets.APIs__GeoCode__Uri }}
          APIs__GeoCode__Key: ${{ secrets.APIs__GeoCode__Key }}
        run: echo Environment variables set
